# Generated by Django 4.1.13 on 2024-01-25 20:31

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', djongo.models.fields.JSONField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuestionario', djongo.models.fields.JSONField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.curso')),
            ],
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=25)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.curso')),
            ],
        ),
    ]
