# Generated by Django 4.1.13 on 2024-01-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='curso',
        ),
    ]
